services:
  # Servicio MongoDB
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio de inicialización (ejecuta scripts una sola vez)
  init-db:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mimic-demo-init
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./scripts:/workspace/scripts
      - ./data:/workspace/data
    environment:
      - MONGO_DEMO_URL=mongodb://mongodb:27017
      - MIMIC_DEMO_PATH=/workspace/data/mimic-iv-clinical-database-demo-2.2
      - ICD_CSV_PATH=/workspace/data/icd_con_equivalencia_ic10_extended.csv
    command: ["/bin/bash", "/workspace/scripts/demo/init-demo.sh"]
    restart: "no"

  # Servicio Backend (FastAPI)
  backend:
    build: ./backend
    depends_on:
      init-db:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - USE_DEMO=true
      - MONGO_DEMO_URL=mongodb://mongodb:27017
      - MONGO_FULL_URL=mongodb://mongodb:27017
    restart: unless-stopped

  # Servicio Frontend (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped

volumes:
  mongodb_data: