version: '3.8'

services:
  # Servicio MongoDB
  mongodb:
    image: mongo:8.0
    container_name: mimic-demo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mimic-network

  # Servicio de inicialización (ejecuta scripts una sola vez)
  init-db:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mimic-demo-init
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./scripts:/workspace/scripts
      - ./icd_con_equivalencia_ic10_extended.csv:/workspace/icd_con_equivalencia_ic10_extended.csv
    environment:
      - MONGO_DEMO_URL=mongodb://mongodb:27017
    command: ["/bin/bash", "/workspace/scripts/demo/init-demo.sh"]
    networks:
      - mimic-network
    restart: "no"

  # Servicio Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mimic-demo-backend
    depends_on:
      init-db:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - USE_DEMO=true
      - MONGO_DEMO_URL=mongodb://mongodb:27017
      - MONGO_FULL_URL=mongodb://mongodb:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - mimic-network
    restart: unless-stopped

  # Servicio Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mimic-demo-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mimic-network
    restart: unless-stopped

networks:
  mimic-network:
    driver: bridge

volumes:
  mongodb_data:
